#!/bin/bash
# Environment setup helper for Jira Plugin

echo "🔧 Jira Plugin Environment Setup"
echo "=================================="
echo ""
echo "Please set the following environment variables:"
echo ""
echo "1. JIRA_URL - Your Jira instance URL"
echo "   Example: https://your-domain.atlassian.net"
echo ""
echo "2. JIRA_EMAIL - Your Jira account email"
echo "   Example: your-email@example.com"
echo ""
echo "3. JIRA_API_KEY - Your Jira API token"
echo "   Generate at: https://id.atlassian.com/manage-profile/security/api-tokens"
echo ""
echo "Add them to your shell profile (.bashrc, .zshrc, .envrc, etc.):"
echo ""
echo "export JIRA_URL='https://your-domain.atlassian.net'"
echo "export JIRA_EMAIL='your-email@example.com'"
echo "export JIRA_API_KEY='your-api-token-here'"
echo ""
echo "Then run: /jira-status"
